// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcC5bwwHdWiHzXSamJcuM4SM3DPMUo8ZA',
    appId: '1:22830959120:web:bc3cdc8c7b85f157251895',
    messagingSenderId: '22830959120',
    projectId: 'multiplayer-tapgame',
    authDomain: 'multiplayer-tapgame.firebaseapp.com',
    storageBucket: 'multiplayer-tapgame.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyNj7SGiAMMX0IUt9vX05DRHl4V2aymio',
    appId: '1:22830959120:android:47eccdf80bac65d1251895',
    messagingSenderId: '22830959120',
    projectId: 'multiplayer-tapgame',
    storageBucket: 'multiplayer-tapgame.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVmnjr6lRItju-WLe9OxxevavvraO1CbE',
    appId: '1:22830959120:ios:1595a48664dfab9d251895',
    messagingSenderId: '22830959120',
    projectId: 'multiplayer-tapgame',
    storageBucket: 'multiplayer-tapgame.firebasestorage.app',
    iosBundleId: 'com.example.tap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVmnjr6lRItju-WLe9OxxevavvraO1CbE',
    appId: '1:22830959120:ios:1595a48664dfab9d251895',
    messagingSenderId: '22830959120',
    projectId: 'multiplayer-tapgame',
    storageBucket: 'multiplayer-tapgame.firebasestorage.app',
    iosBundleId: 'com.example.tap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcC5bwwHdWiHzXSamJcuM4SM3DPMUo8ZA',
    appId: '1:22830959120:web:bc927cc6b36babe8251895',
    messagingSenderId: '22830959120',
    projectId: 'multiplayer-tapgame',
    authDomain: 'multiplayer-tapgame.firebaseapp.com',
    storageBucket: 'multiplayer-tapgame.firebasestorage.app',
  );
}
